---
title: "ASCT kill curves histogram"
output: html_document
date: "2024-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Definig paths
```{r}
wdDir <- getwd()

setwd(wdDir)
resDir <- paste(wdDir,
                "/",
                "Result_Fig",
                sep="")

dataDir <- paste(wdDir,
                "/",
                "ASCT_Data",
                sep="")


```

# Load libraries
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
#install.packages("ggExtra")
library(ggExtra)
library(readxl)
library(reshape2)

library(ggpubr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggforce)
library(RColorBrewer)
library(platetools)
library(directlabels) 
library(MESS)
library(gghighlight)
library(scales)
library(GGally)
library(ggcorrplot)
library(reshape2)
library(plotrix)
library(ggprism)
library(ggrepel)



```

# Loading Data
```{r}
TKC.df <- read.csv(paste(dataDir,
                      "/",
                      "ASCT_part4_PCA-TimeKillCurvesData-TRK_10xMIC_MD.3sd_LINscale.csv",
                      sep=""))


TKC.df <- TKC.df %>%
  mutate(Isolate = gsub("Iso.","", Isolate))

# All OM isolates have to have their names changes. OM = 10 000 so 10 000 + whatever Isolate number
TKC.om.df <- TKC.df %>%
  filter(grepl("OM", Isolate))%>%
  mutate(Isolate = gsub("OM","",Isolate))%>%
  mutate(Isolate = as.numeric(Isolate))%>%
  mutate(Isolate = Isolate + 10000)%>%
  mutate(Isolate = as.character(Isolate))

# Lab strain has to be changed to ATCC
TKC.ATc.df <- TKC.df %>%
  filter(Isolate == "ATc.19979")%>%
  mutate(Isolate ="ATCC")


TKC.df.sub <- TKC.df %>%
  filter(!grepl("OM", Isolate))%>%
  filter(Isolate != "ATc.19979")


TKC.updated.df <- rbind(TKC.df.sub,
                       TKC.ATc.df )

TKC.updated.df <-rbind(TKC.updated.df,
                       TKC.om.df)

TKC.df <- TKC.updated.df

#Houskeeping
rm(TKC.om.df,
   TKC.updated.df,
   TKC.ATc.df,
   TKC.df.sub)

TKC.df <-TKC.df %>%
  mutate(Abx.con = gsub("_",".",Abx.con))%>%
  mutate(Time.Kill.Definitions = gsub("_",".",Time.Kill.Definitions))

TKC.df <-TKC.df %>%
  select(-NormStr,
         -GrowthThreshold,
         -PCA.Strategy,
         -Mahalanobis.Excl.res)
#AUC
AUC.df <- read_excel("/Users/jovanovic/Documents/PhD/Project_Tolerance/Ranalysis/ASCT/ASCT_Figures/ASCT_Main_Data/MainPhenotypes_ASCTpaper.xlsx")

AUC.df <-AUC.df %>%
   select(matches("AUCrt|Isolate"))

AUC.df <- melt(AUC.df ,
               id.vars = "Isolate")

AUC.df <-separate(AUC.df,
                  col = "variable",
                  into = c("Abx.con",
                           "Feature",
                           "Mahalanobis",
                           "Growth.def",
                           "Time.Kill.Definitions",
                           "ExpID"),
                  sep="_")

AUC.df <-AUC.df %>%
  mutate(ExpID.full = ExpID)%>%
  mutate(ExpID = substr(ExpID, 1, 7))

#--- Merging data

TKC.AUC.merged <- left_join(TKC.df,
                            AUC.df)

```

# Fig parameters
```{r}
#--- Y axsis ticks

linear_breaks <- c( 0.40,0.50,0.60 ,0.70,0.80,0.90, 1.0) # Modify this based on your data

# Convert these to log10 scale for the breaks
log_breaks <- log10(linear_breaks)

linear_breaks.label <-  c( 40,50,60 ,70,80,90, 100)
plot.xaxis.time.scale <- c(0,12,24,36,48,60,72)

#---
```

```{r}


rm(combined_plot,
   line_plot,
   plot,
   plot_list,
   TKC.AUC.sub.df,
     TKC.AUC.sub.df.ggside,
   histogram)
# Load necessary libraries
library(gridExtra)
library(ggplot2)


```




# GGside
```{r}
#install.packages("ggside")
library(ggside)
library(ggplot2)
library(patchwork)
library(gridExtra)
library(ggpubr)

# Assuming TKC.AUC.merged is your dataset
list.of.Abx.con <- sort(unique(TKC.AUC.merged$Abx.con))

list.of.Abx.con<- list.of.Abx.con[!grepl("FOX|IPM|IPMc", list.of.Abx.con)]


plot_list <- list()

define.bin.width.var.for.histo <- 0.01
for (i in list.of.Abx.con) {
  # Filter and prepare the data for plotting
  TKC.AUC.sub.df <- TKC.AUC.merged %>%
    ungroup() %>%
    filter(Abx.con == i) %>%
    drop_na() %>%
    mutate(Abx = sub("_.*", "", Abx.con),
           Concentration = sub(".*\\.", "", Abx.con))
  
  
  TKC.AUC.sub.df.ggside <-   TKC.AUC.sub.df %>%
    filter(Mean.Time_Hrs == "72")%>%
    drop_na()


line_plot <- ggplot(TKC.AUC.sub.df, aes(x = Mean.Time_Hrs, y = Mean.LC.fraction.corr, group = Isolate, label = Isolate)) +
  geom_line(alpha = 0.10, size = 0.2) +
  scale_colour_manual(values = c("#293352")) +
  theme_pubr() +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  scale_x_continuous(breaks =c(0,12,24,36,48,60,72))+
  theme(axis.text = element_text(size = 8),
        strip.text.x = element_text(size = 8),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.position = "top",
        aspect.ratio = 1) +
   labs(title = paste(i),
       x = "Time [Hrs]",
       y = "Live cell fraction",
       color = "Condition evaluation")


histogram <- ggplot(TKC.AUC.sub.df.ggside, aes(x = Mean.LC.fraction.corr)) +
  geom_histogram(binwidth = define.bin.width.var.for.histo , fill = "gray", color = "black") +
    geom_density(aes(y=define.bin.width.var.for.histo  * ..count..),
                  fill = "#4E84C4", color = "black", alpha = 0.5) +
  theme_pubr() +

  scale_x_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  scale_y_continuous(breaks = c(0,10,20,30), limits = c(0,30)) +

  coord_fixed(ratio = 1 / diff(range(TKC.AUC.sub.df$Mean.Time_Hrs)) * diff(range(TKC.AUC.sub.df$Mean.LC.fraction.corr))) +
  labs(x = "Live cell fraction at 72h", y = "Count")+
      coord_flip()+
   theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
    guides( y = "none")

  

combined_plot <- line_plot + histogram +
  plot_layout(widths = c(3, 1))  # Adjust these values to align the axes properly




  plot_list[[i]] <- combined_plot
}

# Print and/or save the plots
for (plot in plot_list) {
  print(plot)
}



# Define the number of plots per page
plots_per_page <- 1  # Since each item is a pair of plots managed by patchwork

# Open a PDF file to save the plots
pdf(paste(resDir,
          "/",
          "ASCTfig_TimeKillCurves_LCF72_histo_and_Dens_ALLexceptIPMandFOX.pdf",
          sep=""), width = 11, height = 8.5)

# Loop through the patchworks and plot each one
for (i in seq_along(plot_list)) {
    print(plot_list[[i]])
}

# Close the PDF to ensure the file is saved
dev.off()
```

# ggArrange plots
```{r}
library(ggplot2)
library(patchwork)
# Top 1
p1 <- plot_list[["AMK.10x"]][[1]]
p1.2 <-  plot_list[["AMK.10x"]][[2]]

p2<- plot_list[["AMK.20x"]][[1]]
p2.2 <- plot_list[["AMK.20x"]][[2]]

p3 <- plot_list[["AZM.10x"]][[1]]
p3.2 <- plot_list[["AZM.10x"]][[2]]

p4 <- plot_list[["AZM.20x"]][[1]]
p4.2 <- plot_list[["AZM.20x"]][[2]]

p5clo <- plot_list[["CLO.10x"]][[1]]
p5clo.2 <- plot_list[["CLO.10x"]][[2]]

p5 <- plot_list[["CLO.20x"]][[1]]
p5.2 <- plot_list[["CLO.20x"]][[2]]

p6 <- plot_list[["LZD.10x"]][[1]]
p6.2 <- plot_list[["LZD.10x"]][[2]]

p7 <- plot_list[["LZD.20x"]][[1]]
p7.2 <- plot_list[["LZD.20x"]][[2]]

p8 <- plot_list[["MIN.10x"]][[1]]
p8.2 <- plot_list[["MIN.10x"]][[2]]

p9 <- plot_list[["MIN.20x"]][[1]]
p9.2 <- plot_list[["MIN.20x"]][[2]]

p10 <- plot_list[["MXF.20x"]][[1]]
p10.2 <- plot_list[["MXF.20x"]][[2]]

p11 <- plot_list[["MXFb.10x"]][[1]]
p11.2 <- plot_list[["MXFb.10x"]][[2]]

p12 <- plot_list[["TGC.10x"]][[1]]
p12.2 <- plot_list[["TGC.10x"]][[2]]

pTGC <- plot_list[["TGC.20x"]][[1]]
pTGC.2 <- plot_list[["TGC.20x"]][[2]]



top_plot1 = (p1 + p1.2 + p2 + p2.2 + p3 + p3.2 + p4 + p4.2 +  p5clo + p5clo.2 + p5 + p5.2  ) + plot_layout(ncol = 12)
top_plot1

center_plot1 = ( p6 + p6.2 + p7 + p7.2 + p8 + p8.2 + p9 + p9.2 + p10 + p10.2 +  p11 + p11.2 ) + plot_layout(ncol = 12)
center_plot1 


```




```{r}
# Assuming TKC.AUC.merged is your dataset
list.of.Abx.con <- sort(unique(TKC.AUC.merged$Abx.con))

list.of.Abx.con<- list.of.Abx.con[grepl("FOX|IPM|IPMc", list.of.Abx.con)]


plot_list2 <- list()
#i <- list.of.Abx.con[1]

define.bin.width.var.for.histo <- 0.01
for (i in list.of.Abx.con) {
  # Filter and prepare the data for plotting
  TKC.AUC.sub.df <- TKC.AUC.merged %>%
    ungroup() %>%
    filter(Abx.con == i) %>%
    drop_na() %>%
    mutate(Abx = sub("_.*", "", Abx.con),
           Concentration = sub(".*\\.", "", Abx.con))
  
  
  TKC.AUC.sub.df.ggside <-   TKC.AUC.sub.df %>%
    filter(Mean.Time_Hrs == "72")%>%
    drop_na()

line_plot <- ggplot(TKC.AUC.sub.df, aes(x = Mean.Time_Hrs, y = Mean.LC.fraction.corr, group = Isolate, label = Isolate)) +
  geom_line(alpha = 0.10, size = 0.2) +
  scale_colour_manual(values = c("#293352")) +
  theme_pubr() +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  scale_x_continuous(breaks =c(0,12,24,36,48,60,72))+
  theme(axis.text = element_text(size = 8),
        strip.text.x = element_text(size = 8),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.position = "top",
        aspect.ratio = 1) +
   labs(title = paste(i),
       x = "Time [Hrs]",
       y = "Live cell fraction",
       color = "Condition evaluation")


histogram <- ggplot(TKC.AUC.sub.df.ggside, aes(x = Mean.LC.fraction.corr)) +
  geom_histogram(binwidth = define.bin.width.var.for.histo , fill = "gray", color = "black") +
    geom_density(aes(y=define.bin.width.var.for.histo  * ..count..),
                  fill = "#4E84C4", color = "black", alpha = 0.5) +
  theme_pubr() +

  scale_x_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  scale_y_continuous(breaks = c(0,50,100,150,200), limits = c(0,200)) +

  coord_fixed(ratio = 1 / diff(range(TKC.AUC.sub.df$Mean.Time_Hrs)) * diff(range(TKC.AUC.sub.df$Mean.LC.fraction.corr))) +
  labs(x = "Live cell fraction at 72h", y = "Count")+
      coord_flip()+
   theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
    guides( y = "none")

  

combined_plot <- line_plot + histogram +
  plot_layout(widths = c(3, 1))  # Adjust these values to align the axes properly




 plot_list2[[i]] <- combined_plot
}

# Print and/or save the plots
for (plot in plot_list2) {
  print(plot)
}



# Define the number of plots per page
plots_per_page <- 1  # Since each item is a pair of plots managed by patchwork

# Open a PDF file to save the plots
pdf(paste(resDir,
          "/",
          "ASCTfig_TimeKillCurves_LCF72_histo_and_Dens_IPM.FOXonly.pdf",
          sep=""), width = 11, height = 8.5)

# Loop through the patchworks and plot each one
for (i in seq_along(plot_list2)) {
    print(plot_list2[[i]])
}

# Close the PDF to ensure the file is saved
dev.off()
```



# Combining the ipm and fox plots
```{r}
# Top 1
p13 <- plot_list2[["FOX.10x"]][[1]]
p13.2 <-  plot_list2[["FOX.10x"]][[2]]

p14<- plot_list2[["FOX.20x"]][[1]]
p14.2 <- plot_list2[["FOX.20x"]][[2]]

p15 <- plot_list2[["IPM.10x"]][[1]]
p15.2 <- plot_list2[["IPM.10x"]][[2]]

p16 <- plot_list2[["IPMc.20x"]][[1]]
p16.2 <- plot_list2[["IPMc.20x"]][[2]]

pTGC <- plot_list[["TGC.20x"]][[1]]
pTGC.2 <- plot_list[["TGC.20x"]][[2]]



bottom_plot1 = ( p12 + p12.2 + pTGC + pTGC.2 + p13 + p13.2  + p14 + p14.2 + p15 + p15.2 + p16 + p16.2) + plot_layout(ncol = 12)
bottom_plot1



```


```{r}


Arranged.plot <- ggarrange(top_plot1,
          center_plot1,
          bottom_plot1, 
          #TGC,
         # bottom_plot2,
          
          ncol = 1, nrow = 3)


# Save the multi-page layout to a PDF
ggsave(paste(resDir,
          "/",
          "ASCTfig_TimeKillCurves_LCF72_histo_and_Dens_Allfigs.pdf",
          sep=""), Arranged.plot, width = 20, height = 15)
```




```{r}

```

