---
title: "ASCT kill curves histogram"
output: html_document
date: "2024-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Definig paths
```{r}
wdDir <- getwd()

setwd(wdDir)
resDir <- paste(wdDir,
                "/",
                "Result_Fig",
                sep="")

dataDir <- paste(wdDir,
                "/",
                "ASCT_Data",
                sep="")


```

# Load libraries
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggExtra)
library(readxl)
library(reshape2)

library(ggpubr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggforce)
library(RColorBrewer)
library(platetools)
library(directlabels) 
library(MESS)
library(gghighlight)
library(scales)
library(GGally)
library(ggcorrplot)
library(reshape2)
library(plotrix)
library(ggprism)
library(ggrepel)



```

# Loading Data
```{r}
TKC.df <- read.csv(paste(dataDir,
                      "/",
                      "ASCT_part4_PCA-TimeKillCurvesData-TRK_10xMIC_MD.3sd_LINscale.csv",
                      sep=""))


TKC.df <- TKC.df %>%
  mutate(Isolate = gsub("Iso.","", Isolate))

# All OM isolates have to have their names changes. OM = 10 000 so 10 000 + whatever Isolate number
TKC.om.df <- TKC.df %>%
  filter(grepl("OM", Isolate))%>%
  mutate(Isolate = gsub("OM","",Isolate))%>%
  mutate(Isolate = as.numeric(Isolate))%>%
  mutate(Isolate = Isolate + 10000)%>%
  mutate(Isolate = as.character(Isolate))

# Lab strain has to be changed to ATCC
TKC.ATc.df <- TKC.df %>%
  filter(Isolate == "ATc.19979")%>%
  mutate(Isolate ="ATCC")


TKC.df.sub <- TKC.df %>%
  filter(!grepl("OM", Isolate))%>%
  filter(Isolate != "ATc.19979")


TKC.updated.df <- rbind(TKC.df.sub,
                       TKC.ATc.df )

TKC.updated.df <-rbind(TKC.updated.df,
                       TKC.om.df)

TKC.df <- TKC.updated.df

#Houskeeping
rm(TKC.om.df,
   TKC.updated.df,
   TKC.ATc.df,
   TKC.df.sub)

TKC.df <-TKC.df %>%
  mutate(Abx.con = gsub("_",".",Abx.con))%>%
  mutate(Time.Kill.Definitions = gsub("_",".",Time.Kill.Definitions))

TKC.df <-TKC.df %>%
  select(-NormStr,
         -GrowthThreshold,
         -PCA.Strategy,
         -Mahalanobis.Excl.res)
#AUC
AUC.df <- read_excel("/Users/jovanovic/Documents/PhD/Project_Tolerance/Ranalysis/ASCT/ASCT_Figures/ASCT_Main_Data/MainPhenotypes_ASCTpaper.xls")

AUC.df <-AUC.df %>%
   select(matches("AUCrt|Isolate"))

AUC.df <- melt(AUC.df ,
               id.vars = "Isolate")

AUC.df <-separate(AUC.df,
                  col = "variable",
                  into = c("Abx.con",
                           "Feature",
                           "Mahalanobis",
                           "Growth.def",
                           "Time.Kill.Definitions",
                           "ExpID"),
                  sep="_")

AUC.df <-AUC.df %>%
  mutate(ExpID.full = ExpID)%>%
  mutate(ExpID = substr(ExpID, 1, 7))

#--- Merging data

TKC.AUC.merged <- left_join(TKC.df,
                            AUC.df)

```

# Fig parameters
```{r}
#--- Y axsis ticks

linear_breaks <- c( 0.40,0.50,0.60 ,0.70,0.80,0.90, 1.0) # Modify this based on your data

# Convert these to log10 scale for the breaks
log_breaks <- log10(linear_breaks)

linear_breaks.label <-  c( 40,50,60 ,70,80,90, 100)
plot.xaxis.time.scale <- c(0,12,24,36,48,60,72)



rm(combined_plot,
   line_plot,
   plot,
   plot_list,
   TKC.AUC.sub.df,
     TKC.AUC.sub.df.ggside,
   histogram)
# Load necessary libraries
library(gridExtra)
library(ggplot2)


```
## Single Isolate killing across different drugs
```{r}
# Find all isolates present across all drugs 
n.of.abx.con <- length(unique(TKC.df$Abx.con))

Iso.across.All.drugs <- TKC.AUC.merged %>%
  ungroup()%>%
  select(Abx.con,
         Isolate)%>%
  distinct()%>%
  group_by(Isolate)%>%
  mutate(Present.in.all.drugs = 1,
         Present.in.all.drugs = sum(Present.in.all.drugs),
         Present.in.all.drugs == if_else(Present.in.all.drugs == 18,
                                    "Complete",
                                    "Incomplete"))%>%
  ungroup()%>%
  select(Isolate,
        Present.in.all.drugs )%>%
  distinct()%>%
  filter(Present.in.all.drugs == 18)


Select.Iso <- TKC.df %>%
  left_join(Iso.across.All.drugs)%>%
  drop_na()



Select.Iso <- Select.Iso %>%
  mutate(Concentration = case_when(
    grepl("20x", Abx.con) ~ "20x",
    grepl("10x", Abx.con) ~ "10x",
    TRUE ~ NA_character_  # This will handle any cases that do not match "20x" or "10x"
  ))%>%

  mutate(Abx = sub("\\..*", "", Abx.con))%>%
  mutate(Abx = sub("c","", Abx),
         Abx = sub("b","",Abx))



```

# Export Isolate list
```{r}

Export.Iso.list <- Select.Iso %>%
  select(Isolate)%>%
  distinct()

iso.list.export <- paste(resDir,"/","Isolates.present.across.all.drugs.csv", sep = "")

write.csv(Export.Iso.list  , iso.list.export,
          row.names = FALSE)



```


```{r}
library(ggrepel)
library(ggforce)
library(ggpubr)

Plot.export <- paste(resDir,"/","ASCTfig_Trk_SingleIso_AcrossDrugs_Iso.Abx.pdf", sep = "")

# Define the Zizio palette for Abx
zizio_colors <- c(
  "FOX"  = "#F94144",  # Red (Bactericidal)
  "MXF"  = "#F3722C",  # Orange (Bactericidal)
  "IPM"  = "#F8961E",  # Yellow (Bactericidal)
  "AMK"  = "#F9844A",  # Dark Orange (Bactericidal)
  "TGC"  = "#90BE6D",  # Green (Bacteriostatic)
  "LZD"  = "#43AA8B",  # Teal (Bacteriostatic)
  "MIN"  = "#4D908E",  # Dark Cyan (Bacteriostatic)
  "CLO"  = "#577590",  # Slate Blue (Bacteriostatic)
  "AZM"  = "#277DA1"   # Navy Blue (Bacteriostatic)
)

# Reorder Abx levels to ensure bactericidal drugs are plotted first
Select.Iso$Abx <- factor(Select.Iso$Abx, levels = c("AMK", "FOX", "IPM", "MXF", "TGC", "LZD", "MIN", "AZM"))

# Plot with the Zizio colors and free scales for x and y
gg <- Select.Iso %>%
  filter(Abx != "CLO") %>%  # Filter out CLO if needed
    ggplot(aes(x = Mean.Time_Hrs, 
               y = Mean.LC.fraction.corr, 
               group = Abx.con, 
               label = Isolate,
               color = Abx,
               alpha = Concentration)) +
    geom_line(size = 0.2) +
    theme_pubr() +
    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
    scale_x_continuous(breaks = c(0, 24, 48, 72)) +
    scale_alpha_manual(values = c("20x" = 1, "10x" = 0.5)) +
    scale_color_manual(values = zizio_colors) +
    theme(axis.text = element_text(size = 8),
          strip.text.x = element_text(size = 8),
          strip.background = element_rect(fill = "white", color = "white"), # White background and no border
          legend.key.size = unit(0.1, "cm"),
          legend.key.width = unit(0.1, "cm"),
          legend.position = "top",
          aspect.ratio = 1) +
    labs(
        x = "Time [Hrs]",
        y = "Live cell fraction",
        alpha = "Concentration") +  # Only label the alpha legend
    guides(color = "none") +  # Remove the color legend (for Abx)
    facet_wrap_paginate(~Isolate + Concentration, 
                        ncol = 8,
                        nrow = 5,
                        page = 1)

# Determine the number of pages
n <- n_pages(gg)

# Export the plots to a PDF
pdf(Plot.export, paper = "a4", width = 20, height = 15)
for(i in 1:n) {
    print(gg + facet_wrap_paginate(Isolate ~ Abx, 
                      ncol = 8,
                      nrow = 5, 
                      page = i))
}
dev.off()

# Housekeeping
rm(gg, Plot.export)


```


```{r}
library(ggrepel)
library(ggforce)
library(ggpubr)

Plot.export <- paste(resDir,"/","ASCTfig_Trk_SingleIso_AcrossDrugs_10x20x.pdf", sep = "")

# Define the Zizio palette for Abx
zizio_colors <- c(
  "FOX"  = "#F94144",  # Red (Bactericidal)
  "MXF"  = "#F3722C",  # Orange (Bactericidal)
  "IPM"  = "darkred",  # black (Bactericidal)
  "AMK"  = "#DAA520",  # Dark Yellow (Bactericidal)
  "TGC"  = "#90BE6D",  # Green (Bacteriostatic)
  "LZD"  = "#1D7874",  # Deep Teal (Bacteriostatic)
    "MIN"  = "#577590",  # Slate Blue (Bacteriostatic)
  "CLO"  = "steelblue",  # Slate Blue (Bacteriostatic)
  "AZM"  = "darkblue"   # Navy Blue (Bacteriostatic)
)

# Reorder Abx levels to ensure bactericidal drugs are plotted first
Select.Iso$Abx <- factor(Select.Iso$Abx, levels = c("AMK", "FOX", "IPM", "MXF", "TGC", "LZD", "MIN", "AZM"))

# Plot with the Zizio colors and free scales for x and y
gg <- Select.Iso %>%
  filter(Abx != "CLO") %>%  # Filter out CLO if needed
    ggplot(aes(x = Mean.Time_Hrs, 
               y = Mean.LC.fraction.corr, 
               group = Abx.con, 
               label = Isolate,
               color = Abx,
               alpha = Concentration)) +
    geom_line(size = 0.2) +
    theme_pubr() +
    scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
    scale_x_continuous(breaks = c(0, 24, 48, 72)) +
    scale_alpha_manual(values = c("20x" = 1, "10x" = 0.5), guide = "none") +  # Remove alpha legend
    scale_color_manual(values = zizio_colors) +
    theme(axis.text = element_text(size = 8),
          strip.text.x = element_text(size = 7),
          strip.background = element_rect(fill = "white", color = "white"), # White background and no border
          legend.key.size = unit(0.5, "cm"),
          legend.key.width = unit(0.5, "cm"),
          legend.position = "bottom",  # Position legend at the bottom
          aspect.ratio = 1) +
    labs(
        x = "Time [Hrs]",
        y = "Live cell fraction",
        color = "Antibiotic") +  # Label the color legend for Abx
    guides(alpha = "none") +  # Remove the alpha legend
    facet_wrap_paginate(~Isolate + Concentration,  scales = "free",
                        ncol = 8,
                        nrow = 5,
                        page = 1)

# Determine the number of pages
n <- n_pages(gg)

# Export the plots to a PDF
pdf(Plot.export, paper = "a4", width = 20, height = 15)
for(i in 1:n) {
    print(gg + facet_wrap_paginate(Isolate ~ Concentration, scales = "free",
                      ncol = 8,
                      nrow = 5, 
                      page = i))
}
dev.off()

# Housekeeping
rm(gg, Plot.export)


```


