
# SECTION 1: defining variables 
```{r setup, include=FALSE}


info.wdDir <- getwd()
info.wdDir <- setwd(info.wdDir)
info.resDir <- paste(info.wdDir,
                     "/Result-Fig",
                     sep="")

info.trk.dir <- paste(info.wdDir,
                "/Experimental-Results/STTL.14.20240705_Trkv2_LCF_flags.csv",sep="")

info.lcf72h.dir <-  paste(info.wdDir,
                "/Experimental-Results/STTL.14.20240705_Trkv2_rawKF.csv",sep="")
```

#SECTION 2:  Loading packages 
```{r}
library(ggpubr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggforce)
library(platetools)
library(directlabels) 
library(MESS)
library(gghighlight)
library(reshape2)
library(scales)

library(ggprism)
```

# Load tracking data
```{r}

# Exclude growth only

Trk.df <- read.csv(info.trk.dir )

Trk.df <- Trk.df %>%
  mutate(Abx.con2 = gsub("per", "µl ",Abx.con),
         Abx.con2 = gsub("g", " gel.height:", Abx.con2),
         Abx.con2 = gsub("_", "% ", Abx.con2),
         Abx.con2 = gsub("µl ", "µl  gel.percent:0.", Abx.con2),
         Abx.con2 = gsub(" ", "_",Abx.con2),
          Abx.con2 = gsub("__", "_",Abx.con2)
         )

Trk.df <-separate(Trk.df, col = Abx.con2, 
                  into = c("Abx",
                           "Gel.height",
                           "Gel.percent",
                           "Concentration"),
                           sep="_")

Trk.df <-Trk.df %>%
  filter(Killing.Def == "Trkv2_LCF_Ila2BaSic")%>%
  filter(T_Eval_Trck.Numbers == ">1K")%>%
  select(ExpFile,
         Well_coordinate,
         Abx,
         Concentration,
         Gel.height,
         Gel.percent,
         Time_Hrs,
         timestep,
         Flag.label,
         LC.fraction.corr)

abx.list <- unique(Trk.df$Abx)


Trk.df <- Trk.df %>%
  mutate(Gel.height = gsub("gel.height:",
                           "",
                           Gel.height),
         Gel.percent = gsub("gel.percent:",
                            "",
                            Gel.percent))%>%
  mutate(Gel = paste(Gel.height,
                     Gel.percent,
                     sep ="_"))


gel.h <- unique(Trk.df$Gel.height)
gel.h


gel.per <-  unique(Trk.df$Gel.percent)
gel.per 


gel.composition <-unique( paste(Trk.df$Gel.height,
                         "_",
                         Trk.df$Gel.percent,
                         sep=""))

sort(gel.composition)

```

```{r}
Trk.df.KillCurveONLY <- Trk.df %>%
  select(ExpFile,
         Well_coordinate,
         Time_Hrs,
         timestep,
         LC.fraction.corr)


Trk.df <- Trk.df %>%
  select(-Time_Hrs,
         -LC.fraction.corr)

```



# Live cell fraction at 72h
```{r}

LCF.72h <- read.csv(info.lcf72h.dir)

LCF.72h <- LCF.72h %>%
  filter(Main.KF == "LCF")%>%
  filter(Sub.KF == "72h")%>%
  mutate(timestep = 31)%>%
  mutate(LC.fraction.corr = value)%>%
  mutate(Time_Hrs = 72)%>%
  select(ExpFile,
         Well_coordinate,
         Time_Hrs,
         timestep,
         LC.fraction.corr)


Trk.df.KillCurveONLY<- rbind(Trk.df.KillCurveONLY,
                    LCF.72h)

Trk.df <- Trk.df  %>%
  select(-timestep)

```



```{r}

Trk.df <- left_join(Trk.df,
                    Trk.df.KillCurveONLY,
                    by = c("ExpFile",
                           "Well_coordinate"))


rm(LCF.72h,
   Trk.df.KillCurveONLY)
```





# Mean overview
```{r}
Trk.MEAN.df <- Trk.df %>%
  ungroup()%>%
  mutate(Condition = paste(Abx,
                           Concentration,
                           Gel.height,
                           Gel.percent,
                           sep="_"))%>%
  group_by(Condition,
          timestep)%>%
  
  mutate(Mean_Time_Hrs =  mean(Time_Hrs),
         Mean_LC.fraction.corr = mean(LC.fraction.corr))%>%
  select(-Well_coordinate,
         -LC.fraction.corr,
         -Time_Hrs,
         -timestep)%>%
  distinct()
```


# LB: Plot gel 5µl colour by percent
```{r}


Plot.export <- paste(info.resDir,"/","ASCTfig_Reproducibility_Split_Abx-Conc_gelhi.5µl_colgelPerc_LB-1.pdf", sep = "")

# Define the Zizio palette for Abx
zizio_colors <- c(
  "0.3%" = "#1E90FF",  # Dodger Blue
  "0.4%" = "#FF0000" ,  # Red
  "0.5%" = "black"   # Red
)

# Reorder Abx levels to ensure bactericidal drugs are plotted first
Trk.df$Abx <- factor(Trk.df$Abx, levels = c("AMK", "FOX", "IPM", "MXF", "TGC", "LZD", "MIN"))

# Plot with the Zizio colors and free scales for x and y
gg <- Trk.df %>%
  filter(Gel.height == "5µl") %>%
  ggplot(aes(x = Time_Hrs, 
             y = LC.fraction.corr, 
             group = Well_coordinate, 
             color = Gel.percent)) +
  geom_line(size = 0.1) +
  theme_pubr() +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), limits = c(0, 1)) +
  scale_x_continuous(breaks = c(0, 24, 48, 72)) +
  scale_color_manual(values = zizio_colors) +
  theme(axis.text = element_text(size = 8),
        strip.text.x = element_text(size = 8),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.position = "bottom", # Move legend to the bottom
        legend.direction = "horizontal", # Arrange the legend horizontally
        aspect.ratio = 1) +
  labs( title = "Time kill kinetics of 5µl gel height across gel concentrations",
    x = "Time [Hrs]",
    y = "Live cell fraction",
    color = "Gel percent" # Label for the color legend
  ) +
  facet_wrap_paginate(Abx ~ Concentration + Gel.height, 
                      ncol = 7,
                      nrow = 2,
                      page = 1)

# Determine the number of pages
n <- n_pages(gg)

# Export the plots to a PDF
pdf(Plot.export, paper = "a4", width = 20, height = 15)
for (i in 1:n) {
  print(gg + facet_wrap_paginate(Abx ~ Concentration + Gel.height, 
                                 ncol = 7,
                                 nrow = 2, 
                                 page = i))
}
dev.off()

# Housekeeping
rm(gg, Plot.export)

```



# LB: Plot gel 5µl colour by percent PaC: FOX , LZ, MXF 10x

```{r}


Plot.export <- paste(info.resDir,"/","ASCTfig_Reproducibility_Split_Abx-Conc_gelhi.5µl_colgelPerc_PAC.1.pdf", sep = "")

# Define the Zizio palette for Abx
zizio_colors <- c(
  "0.3%" = "grey",  # Dodger Blue
  "0.4%" = "steelblue" ,  # Red
  "0.5%" = "darkblue"   # Red
)

# Reorder Abx levels to ensure bactericidal drugs are plotted first
Trk.df$Abx <- factor(Trk.df$Abx, levels = c("AMK", "FOX", "IPM", "MXF", "TGC", "LZD", "MIN"))

# Plot with the Zizio colors and free scales for x and y
gg <- Trk.MEAN.df %>%
  filter(Gel.height == "5µl") %>%
  ggplot(aes(x = Mean_Time_Hrs, 
             y = Mean_LC.fraction.corr, 
              group = Condition, 
             color = Gel.percent)) +
  geom_line(size = 0.5) +
  theme_prism(base_line_size = 8/14) +
  scale_y_continuous(breaks = c(0,0.5, 1), limits = c(0, 1)) +
  scale_x_continuous(breaks = c(0, 24, 48, 72)) +
  scale_color_manual(values = zizio_colors) +
  theme(axis.text = element_text(size = 8),
        axis.ticks = element_blank(),
        strip.text.x = element_text(size = 8),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.position = "right", # Move legend to the right
        legend.direction = "vertical", # Arrange the legend vertically
        aspect.ratio = 1) +
  labs( title = "",
    x = "Time [Hrs]",
    y = "Live cell fraction",
    color = "Gel percent" # Label for the color legend
  ) +
  facet_wrap_paginate( Concentration ~ Abx , 
                      ncol = 7,
                      nrow = 2,
                      page = 1)

# Determine the number of pages
n <- n_pages(gg)

# Export the plots to a PDF
pdf(Plot.export, paper = "a4", width = 20, height = 15)
for (i in 1:n) {
  print(gg + facet_wrap_paginate(Concentration ~ Abx , 
                                 ncol = 7,
                                 nrow = 2, 
                                 page = i))
}
dev.off()

# Housekeeping
rm(gg, Plot.export)

```


```{r}

Plot.export <- paste(info.resDir,"/","ASCTfig_Reproducibility_Split_Abx-Conc_SingleGelperc_differentVolume_colgel0.4percent_PAC.2.pdf", sep = "")

zizio_colors <- c(
  "3µl" = "#4682B4",  # Steel Blue (muted blue)
  "4µl" = "#87CEFA",  # Light Sky Blue
  "5µl" = "#F0E68C",  # Khaki (muted yellow)
  "6µl" = "#FFB347",  # Pastel orange
  "7µl" = "#CD5C5C"   # Indian Red (muted red)
)

# Reorder Abx levels to ensure bactericidal drugs are plotted first
Trk.df$Abx <- factor(Trk.df$Abx, levels = c("AMK", "FOX", "IPM", "MXF", "TGC", "LZD", "MIN"))

# Plot with the Zizio colors and free scales for x and y
gg <- Trk.MEAN.df %>%
  filter(Gel.percent == "0.4%")%>%
  filter(Gel.height != "3µl")%>%
  ggplot(aes(x = Mean_Time_Hrs, 
             y = Mean_LC.fraction.corr, 
              group = Condition, 
             color = Gel.height)) +
  geom_line(size = 0.5) +
  theme_prism(base_line_size = 8/14) +
  scale_y_continuous(breaks = c(0,0.5, 1), limits = c(0, 1)) +
  scale_x_continuous(breaks = c(0, 24, 48, 72)) +
  scale_color_manual(values = zizio_colors) +
  theme(axis.text = element_text(size = 8),
        axis.ticks = element_blank(),
        strip.text.x = element_text(size = 8),
        strip.background = element_rect(fill = "white", color = "white"),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.position = "right", # Move legend to the right
        legend.direction = "vertical", # Arrange the legend vertically
        aspect.ratio = 1) +
  labs( title = "",
    x = "Time [Hrs]",
    y = "Live cell fraction",
    color = "Gel height" # Label for the color legend
  ) +
  facet_wrap_paginate( Concentration ~ Abx + Gel.percent, 
                      ncol = 7,
                      nrow = 2,
                      page = 1)

# Determine the number of pages
n <- n_pages(gg)

# Export the plots to a PDF
pdf(Plot.export, paper = "a4", width = 20, height = 15)
for (i in 1:n) {
  print(gg + facet_wrap_paginate(Concentration ~ Abx , 
                                 ncol = 7,
                                 nrow = 2, 
                                 page = i))
}
dev.off()

# Housekeeping
rm(gg, Plot.export)

```




