---
title: "ASCT_check_MAB_associations"
output: html_document
date: "2024-10-15"
---
Aim: load the main data table for ASCT tolerance do the mann whitney calculation across the select drug conditons for clinical outcome

# 1. Set directories
```{r}

info.wd <- getwd()

info.resDir <- paste(info.wd,
                     "/Fig_results/",
                     sep="")


info.dataDir <- c("/Users/jovanovic/Documents/PhD/Project_Tolerance/Ranalysis/ASCT/ASCT_Figures/ASCT_Main_Data/MainPhenotypes_ASCTpaper.csv") 
```
# 2. Load libraries
```{r}

library(ggpubr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggforce)
library(RColorBrewer)
library(platetools)
library(directlabels)
library(MESS)
library(gghighlight)
library(scales)
library(GGally)
library(ggcorrplot)
library(reshape2)
library(plotrix)
library(ggprism)
library(ggrepel)
library(stringr)
library(readxl)
library(rstatix)
library(ggExtra)


library(grid)  # Load the grid package allows you to add text to pages in ggplot

```

# 3. Load main data
```{r}
Main.df <- read.csv(info.dataDir)

ASCT.tol <- Main.df %>%
  select( ClearedVSpersistant_ATS,
         matches("_MD.3sd_Growth.Q1Q2_Trkv2.Ila2BaSic_"),
          matches("_MIC_lg2"))

```

# 3.1 Select key variables and perform mann whitney U test
```{r}

list.of.variables <- names(ASCT.tol)
list.of.variables <- setdiff(list.of.variables, "ClearedVSpersistant_ATS")

var <- list.of.variables[1]

ASCT.tol.stats <- data.frame()


for ( var in list.of.variables ) {
  
  ASCT.tol.sub <- ASCT.tol %>%
    select(ClearedVSpersistant_ATS,
           var)%>%
    drop_na()%>%
     wilcox_test(
      formula = as.formula(paste(var, "~ ClearedVSpersistant_ATS")),
          paired = FALSE,
                alternative = "two.sided"
  
    )%>%
    select(-statistic)%>%
    mutate(Stat.test = "Mann.Whitney")
  
  
  ASCT.tol.stats <- rbind(ASCT.tol.stats,
                            ASCT.tol.sub)
  
                 
}


# Get the current date and time in YYYYMMDD_HH format
current_date_time <- format(Sys.time(), "%Y%m%d_%H")


```

# 4. Mann whitney U test
```{r}
write.csv(ASCT.tol.stats , 
          paste(info.resDir,"ASCT_MABassociation_mwu.statistics_",current_date_time,".csv",sep=""), row.names = FALSE)
```

# 5. Export result table
```{r}

```

