---
title: "ASCTimganalysis_singlefield_outlook"
author: "Alex"
date: "2025-04-10"
output: html_document
---


#1. Load libraries
```{r}
library(tidyr)
library(dplyr)
library(readxl)
library(reshape2)
library(ggplot2)
library(ggpubr)
```

#2. Define paths
```{r}

info.wd <- getwd()
info.imgdata.res.dir <- file.path(getwd(), "..", "..", "1_ASCT_image_analysis", "Data")
info.list.of.imgdata.dir <- list.dirs("../../1_ASCT_image_analysis/Data",
                                      full.names = TRUE, 
                                      recursive = FALSE)

info.list.of.field.dir <- sub("^.*Data/",
                              "",
                              info.list.of.imgdata.dir)


```

#3. Create data analysis directories

```{r}
for (i in info.list.of.imgdata.dir) {
  for (j in info.list.of.field.dir) {

    source_dir <- file.path(i)
    target_dir <- file.path(getwd(), j)
    file_names <- list.files(source_dir)

    ## 1. Metadata
    metadata_dir <- file.path(target_dir, paste0(j, "_Metadata"))
    dir.create(metadata_dir, recursive = TRUE, showWarnings = FALSE)
    file.copy(
      from = file.path(source_dir, grep("Metadata\\.csv$", file_names, value = TRUE)),
      to = metadata_dir,
      overwrite = TRUE
    )

    ## 2. MOC
    moc_dir <- file.path(target_dir, paste0(j, "_OCsimple.moc"))
    dir.create(moc_dir, recursive = TRUE, showWarnings = FALSE)
    file.copy(
      from = file.path(source_dir, grep("^MOC-.*\\.csv$", file_names, value = TRUE, ignore.case = TRUE)),
      to = moc_dir,
      overwrite = TRUE
    )

    ## 3. POC
    poc_dir <- file.path(target_dir, paste0(j, "_OCsimple.poc"))
    dir.create(poc_dir, recursive = TRUE, showWarnings = FALSE)
    file.copy(
      from = file.path(source_dir, grep("^POC-.*\\.csv$", file_names, value = TRUE, ignore.case = TRUE)),
      to = poc_dir,
      overwrite = TRUE
    )

    ## 4. Tracking
    tracking_dir <- file.path(target_dir, paste0(j, "_Tracking_labeloid"))
    dir.create(tracking_dir, recursive = TRUE, showWarnings = FALSE)
    file.copy(
      from = file.path(source_dir, grep("^CorrectedTrackTable_.*\\.csv$", file_names, value = TRUE, ignore.case = TRUE)),
      to = tracking_dir,
      overwrite = TRUE
    )
    
    
    results_dir <- file.path(getwd(), j, paste0(j, "_Results"))
dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)
  }
}

#Houskeeping
# Keep all variables that start with "info." plus any others you want to preserve
vars_to_keep <- grep("^info\\.", ls(), value = TRUE)
vars_to_keep <- c(vars_to_keep)  # Add "i", "j" if needed

# Remove everything else
rm(list = setdiff(ls(),
                  vars_to_keep))

#Houskeeping
# Keep all variables that start with "info." plus any others you want to preserve
vars_to_keep <- grep("^info\\.", ls(), value = TRUE)
vars_to_keep <- c(vars_to_keep)  # Add "i", "j" if needed

# Remove everything else
rm(list = setdiff(ls(),
                  vars_to_keep))
```

## 3.1  Transforming tracking output to long format
```{r}
# load Tracking output
i<- info.list.of.field.dir
for ( i in info.list.of.field.dir ) {
  
  
      #----- transfroming tracking output to long format ----
      source_data_dir <- file.path(getwd(),
                              i,
                              paste(i,"_Tracking_labeloid",sep=""))
      
      source_data_dir <- paste(      source_data_dir,
                                           "/CorrectedTrackTable_",
                                           i,
                                           ".csv",sep="")

      trk.df <- read.csv(      source_data_dir)
      
      
     trk.df <-  trk.df %>%
       mutate(ExpID_Well_Field = i,
              TrackID = time.frame.1.ID.label )
     
      trk.df <- trk.df %>%
  pivot_longer(
    cols = starts_with("time.frame."),
    names_to = "timestep",
    values_to = "labelimage_oid"
  ) %>%
  mutate(
    timestep = gsub("time.frame.", "", timestep),
        timestep = gsub(".ID.label", "", timestep),

    
    timestep= as.integer(timestep))%>%
  select(ExpID_Well_Field,
         TrackID, 
         timestep,
         labelimage_oid )
      
      source_data_dir <- file.path(getwd(),
                              i,
                              paste(i,"_Tracking_labeloid",sep=""))
      
     
  
      write.csv(      trk.df, file = paste(    source_data_dir,
                                           "/Dynamic_Table_corrected_",
                                           i,
                                           ".csv",
                                           sep=""))
      
            trk.df <- trk.df %>%
            mutate(timestep = timestep -1)
        #----- Loading Metadata for integration 
      source_data_dir <- file.path(getwd(),
                              i,
                              paste(i,"_Metadata",sep=""))
      
      
      metadata.df <- read.csv(file = paste(    source_data_dir,
                                           "/",
                                           i,
                                           "_Metadata.csv",
                                           sep="") )
      
  metadata.df <- metadata.df %>%
  rename(timestep = sep.) %>%
  mutate(
    timestep = as.numeric(gsub("TimeStamp ", "", timestep)),
    Time_Hrs = as.numeric(X) / 3600
  ) %>%
       drop_na()%>%
    mutate(timestep = timestep -1)%>%
  select(timestep,
         Time_Hrs)
  
     #----- Loading viability information to merge with tracking
  
  #Irrespective of the number of rows bind all the elemtents of my list using a unique identifier "well_coord" which is based on the name of each element of the list 
   
    #----- Loading ilastik cell viability  output for integration 
      source_data_dir <- file.path(getwd(),
                              i,
                              paste(i,"_OCsimple.poc",sep=""))
      
       ASCT.poc.df <- read.csv(file = paste(    source_data_dir,
                                           "/POC-",
                                           i,
                                           "_FLcorr_table.csv",
                                           sep="") )
       
       

  ASCT.poc.df <- ASCT.poc.df %>%
 dplyr::mutate(POC.Predicted.Class = Predicted.Class)%>%
    dplyr::mutate(Mean.IntensityBaSic = Mean.Intensity)%>%
    mutate(ExpID = i)%>%
    select(ExpID,
           object_id,
           timestep,
           labelimage_oid,
           POC.Predicted.Class,
           Mean.IntensityBaSic,
           Center.of.the.object_0,
           Center.of.the.object_1)
  
  
    ASCT.poc.df <- ASCT.poc.df %>%
      mutate(ExpID_Well_Field = ExpID)%>%
  separate(ExpID, into = c("ExpID", 
                           "Well_coordinate", 
                           "Field"), sep = "_", remove = FALSE)
    


  ASCT.poc.df <- ASCT.poc.df %>%
    dplyr::mutate(Field = as.numeric(gsub("p","",Field)))%>%
  select_if(~!all(is.na(.))) 
  
  
  
matlab.trk.df <- left_join(trk.df,
                           ASCT.poc.df)
 
     matlab.trk.df <- matlab.trk.df  %>%
       select(ExpID_Well_Field,
              ExpID,
              Well_coordinate,
              Field,
              timestep,
              labelimage_oid,
              TrackID,
              object_id,
              POC.Predicted.Class,
              Mean.IntensityBaSic)
     
     
    matlab.trk.df <- matlab.trk.df %>%
dplyr::ungroup() %>%
     group_by(Well_coordinate, 
              Field, 
              TrackID) %>%
    dplyr::mutate(NAs_in_Ila_Mean_Intensity = sum(is.na(Mean.IntensityBaSic)))%>%
  dplyr::mutate(Consecutive_NAs = ifelse(is.na(Mean.IntensityBaSic) & 
                                         (is.na(lag(Mean.IntensityBaSic)) | 
                                            is.na(lead(Mean.IntensityBaSic))), 
                                       1,0))%>%
    dplyr::mutate(Sum.of.Consecutive_NAs = sum(Consecutive_NAs))%>%
    dplyr::ungroup()%>%
    filter(Sum.of.Consecutive_NAs <= 2)%>%
    filter(NAs_in_Ila_Mean_Intensity <= 6)%>%
  dplyr::ungroup()%>%
 group_by(Well_coordinate,
             Field,
             TrackID)%>% # MF abbreviation for Missing Frames ; if MF then check the previous Frame and apply the POC (pi/viability classification) of the previous frame. Repeat this 6 times so we do not have missing values
    dplyr::mutate(Mean.IntensityBaSic.MF1 = if_else(is.na(Mean.IntensityBaSic), lag(Mean.IntensityBaSic), Mean.IntensityBaSic),
           Mean.IntensityBaSic.MF2 = if_else(is.na(Mean.IntensityBaSic.MF1 ), lag(Mean.IntensityBaSic.MF1 ), Mean.IntensityBaSic.MF1),
           Mean.IntensityBaSic.MF3 = if_else(is.na(Mean.IntensityBaSic.MF2 ), lag(Mean.IntensityBaSic.MF2 ), Mean.IntensityBaSic.MF2),
           Mean.IntensityBaSic.MF4 = if_else(is.na(Mean.IntensityBaSic.MF3 ), lag(Mean.IntensityBaSic.MF3 ), Mean.IntensityBaSic.MF3),
           Mean.IntensityBaSic.MF5 = if_else(is.na(Mean.IntensityBaSic.MF4 ), lag(Mean.IntensityBaSic.MF4 ), Mean.IntensityBaSic.MF4),
           Mean.IntensityBaSic.MF6 = if_else(is.na(Mean.IntensityBaSic.MF5 ), lag(Mean.IntensityBaSic.MF5 ), Mean.IntensityBaSic.MF5))%>%
 dplyr::mutate(POC.Predicted.Class.MF1 = if_else(is.na(POC.Predicted.Class), lag(POC.Predicted.Class), POC.Predicted.Class),
           POC.Predicted.Class.MF2 = if_else(is.na(POC.Predicted.Class.MF1 ), lag(POC.Predicted.Class.MF1 ), POC.Predicted.Class.MF1),
           POC.Predicted.Class.MF3 = if_else(is.na(POC.Predicted.Class.MF2 ), lag(POC.Predicted.Class.MF2 ), POC.Predicted.Class.MF2),
           POC.Predicted.Class.MF4 = if_else(is.na(POC.Predicted.Class.MF3 ), lag(POC.Predicted.Class.MF3 ), POC.Predicted.Class.MF3),
           POC.Predicted.Class.MF5 = if_else(is.na(POC.Predicted.Class.MF4 ), lag(POC.Predicted.Class.MF4 ), POC.Predicted.Class.MF4),
           POC.Predicted.Class.MF6 = if_else(is.na(POC.Predicted.Class.MF5 ), lag(POC.Predicted.Class.MF5 ), POC.Predicted.Class.MF5))%>%
   select(
           Well_coordinate,
           Field,
           TrackID,
           timestep,
           ExpID_Well_Field,
           Mean.IntensityBaSic,
           Mean.IntensityBaSic.MF6,
           POC.Predicted.Class,
           POC.Predicted.Class.MF6)%>%
 dplyr::ungroup()%>%
    dplyr::mutate(Mean.IntensityBaSic = Mean.IntensityBaSic.MF6,
           POC.Predicted.Class = POC.Predicted.Class.MF6)%>%
    select(-Mean.IntensityBaSic.MF6,
           -POC.Predicted.Class.MF6)




#----- Ilastik 2: Twice positive always postive: if trackID in terms of viability assessment is classified ad piPosistive for two consecutive timepoints then the trackID from the first instance of piPOS is classified piPOS for the rest of the info.timelapse


matlab.trk.df <- matlab.trk.df %>%
    dplyr::ungroup() %>%
    group_by(ExpID_Well_Field,
             Well_coordinate,
             Field,
             TrackID) %>%
    dplyr::mutate(Predicted_Class_Pi_Pos = if_else(POC.Predicted.Class == "piPOS", 1, 0)) %>%
    dplyr::mutate(Consecutive_Pi_Pos = if_else(lead(Predicted_Class_Pi_Pos) == 1 & Predicted_Class_Pi_Pos == 1, 1, 0)) %>%
    dplyr::mutate(Consecutive_Pi_Pos_Count = cumsum(Consecutive_Pi_Pos)) %>%
    dplyr::mutate(Predicted_Class_Status = if_else(Consecutive_Pi_Pos_Count >= 1, "piPOS", "piNEG")) %>%
    dplyr::ungroup() %>%
    group_by(Well_coordinate,
             Field,
             TrackID,
             timestep) %>%
    dplyr::mutate(POC.Predicted.Class = if_else(timestep == max(timestep) && is.na(Predicted_Class_Status), "piPOS", as.character(Predicted_Class_Status)))%>%
    dplyr::ungroup()%>%
  dplyr::mutate(Exp_Well_Field_TrackID = paste(ExpID_Well_Field,
                                       TrackID))%>%
    select(
      -Consecutive_Pi_Pos,
      -Consecutive_Pi_Pos_Count,
      -Predicted_Class_Status,
      -Predicted_Class_Pi_Pos)



  # ---- Calculate ilastik live cell fraction 
  
  #--- Pi POS Neg numbers
  Tracking_LCF <-  matlab.trk.df%>%
    dplyr::select(
   Exp_Well_Field_TrackID,
   ExpID_Well_Field,
      Well_coordinate,
      Field,
      TrackID,
      timestep,
      POC.Predicted.Class)%>%
    dplyr::ungroup()%>%
    dplyr::group_by(
      ExpID_Well_Field,
      timestep,
       POC.Predicted.Class) %>%
    summarise(n = n()) %>%
    dplyr::mutate(Trk_LCF = n/sum(n)) %>%
    dplyr::mutate(Trk_Number = n)%>%
    dplyr::select(-n)%>%
    dplyr::ungroup()%>%
  group_by(ExpID_Well_Field, timestep) %>%
  summarise(
    Trk_uncorr.frac.piNEG_frac.piPOS = paste(
      if_else(POC.Predicted.Class == "piNEG", 
              paste(Trk_LCF, sep = ""), 
              paste( Trk_LCF, sep = "")), 
      collapse = "_"
    ),
   Trk_n.piNEG_n.piPOS = paste(
      if_else(POC.Predicted.Class == "piNEG", 
              paste(Trk_Number,  sep = ""), 
              paste(Trk_Number,  sep = "")), 
      collapse = "_"
    ),
   Trk_Tot.N = sum(Trk_Number)
  ) %>%
  ungroup()

# Adding time metadata


Tracking_LCF <- left_join(Tracking_LCF,
                         metadata.df)

Tracking_LCF <-Tracking_LCF %>%
  mutate(LC_fraction =  as.numeric(sub("_.*", "", Trk_uncorr.frac.piNEG_frac.piPOS)),
         ExpID_Well_Field = unique(matlab.trk.df$ExpID_Well_Field))%>%
  select(ExpID_Well_Field ,
         timestep,
         Time_Hrs,
         LC_fraction,
         everything())

# Plotting time kill curve 
info.plot.xaxis.time.scale <- c(0,12,24,36,48,60,72)

p1.timekillcurve.plot <- Tracking_LCF  %>%
  distinct() %>%

  ggplot(aes(x = Time_Hrs,
             y = LC_fraction,
             group = ExpID_Well_Field,
             label =ExpID_Well_Field)) +

  geom_line(alpha = 0.5, size = 1,
            colour = "Steelblue") +

  geom_point( size = 1,
              stroke = 0) +




  scale_y_continuous(
    breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),
    limits = c(0, 1),
    name = "Fraction of cells alive"
  ) +

  scale_x_continuous(
    breaks = info.plot.xaxis.time.scale,
    name = "Time (hrs)"
  ) +
 labs(title = paste("Time kill curve of: ",
                unique(Tracking_LCF$ExpID_Well_Field),
                sep=""),
      subtitle = paste("Number of tracked cells:", unique(Tracking_LCF$Trk_Tot.N)))+
  theme_pubr() +
  theme(
    legend.position = c(0.4, 0.70),             # moved legend leftward
    legend.justification = c(0, 1),
    legend.direction = "vertical",
    legend.title = element_blank(),
    legend.key.size = unit(0.3, "cm"),
    legend.key.width = unit(0.5, "cm"),
    legend.text = element_text(size = 8),

    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.text = element_blank(),
    axis.text = element_text(size = 9),
    plot.margin = margin(10, 10, 10, 10)
  )
p1.timekillcurve.plot

      source_data_dir <- file.path(getwd(),
                              i,
                              paste(i,"_Results",sep=""))

  source_data_dir <- paste(      source_data_dir,
                                           "/",
                                           i,
                                           "_SingleField_Results.plot.pdf",sep="")

# Save the plot
ggsave(filename =  source_data_dir,
       plot = p1.timekillcurve.plot,
       width = 6,
       height = 6,
       units = "in",
       device = pdf) 

     
}



```


```{r}

```

